In [10]:
import numpy as np

In [11]:
arr = np.array([348,35,366,4,52,656,"hi"])
print(arr[5])

656


# Dimensions(nested array)

## 0dim - () - collection of elements.
## 1dim - [1,2,3] - collection of 0dim items
## 2dim - [[1,2,3],[4,5,6]] - collection of 1dim items
## 3dim - [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]] - collection of 2dim items
## Multidim - [ [ [ [ [ [ ] ] ] ] ] ] 

In [12]:
arr = np.array([[348,35,366,4,52,656,0],[234,6,3,566,155,34,5]])
print(arr[1,3])

566


In [13]:
print(arr.astype(bool))

[[ True  True  True  True  True  True False]
 [ True  True  True  True  True  True  True]]


In [14]:
copyitem = arr.copy()
print(copyitem)

[[348  35 366   4  52 656   0]
 [234   6   3 566 155  34   5]]


In [15]:
for i in copyitem:
    add = i*2
    for j in add:
        print(j)

696
70
732
8
104
1312
0
468
12
6
1132
310
68
10


## create multidimsions

In [16]:
multdim = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]],ndmin = 5)
print(multdim)


[[[[[ 1  2  3  4  5  6]
    [ 7  8  9 10 11 12]]]]]


## show dim

In [17]:
print(multdim.ndim)

5


In [30]:
v = "hi , this is manikandan"
v= v.split(' is ')
print(v)

['hi , this', 'manikandan']


In [45]:
print(multdim[0,0,0,1,4])

11


In [46]:
print(multdim[0,0,0,1,1:3])

[8 9]
